### PR TITLE
Added options to use alert dialog and set width of alert dialog and modalBottomSheet

### PR DESCRIPTION
**Pull request by alexrabin**
Added options to use a full screen alert dialog instead of bottom sheet and set width of alert dialog or bottom sheet.

 Also updated macOS example project to allow making outgoing connections to call giphy api.

Screenshot 2024-12-12 at 3 42 50 PM
Screenshot 2024-12-12 at 3 42 59 PM

Set fullscreen width for bottom sheet
Screenshot 2024-12-13 at 9 38 33 AM

### CODE REVIEW

**Comment by maxland255** [comment]
Thanks for your interest and your contribution to this project!

I've analyzed your pull request, but I'm wondering if we could achieve this functionality in a different way. Could you perhaps achieve the desired full-screen effect by configuring the existing ModalBottomSheet instead?

**Comment by alexrabin** [comment]
Could we do both options? The modal bottom sheet doesn't look natural on desktop

**Comment by alexrabin** [comment]
@maxland255 we can change the method names to showModalBottomSheet and showAlertDialog and add in the config a property for the width?

**Comment by alexrabin** [comment]
@maxland255 I updated the branch to include a width option in the config so the user can set the width accordingly for either the bottom sheet or the alert dialog. Let me know your thoughts

**Comment by maxland255** [comment]
This is a good idea.
It's just an idea but if in the showDialog you remove AlertDialog and return directly the Giphy view, the view is in full screen and you don't have border created by the AlertDialog?
Sorry if my comment is not perfectly worded, I don't have my pc with me now 😅

**Comment by alexrabin** [comment]
If you remove the AlertDialog widget the Giphy widget will be full screen. The point of having the showAlertDialog is to have the Giphy widget in a dialog.

Without the AlertDailog:
Screenshot 2024-12-13 at 10 16 02 AM

With the AlertDialog:
Screenshot 2024-12-12 at 3 42 59 PM

**Comment by maxland255** [comment]
Okay

I juste have a question, why in the dialog you have a vertical line in an other colour between the background of Giphy widget on the left side ?

**Comment by alexrabin** [comment]
Ah good catch, that looks like it is coming from the MaterialApp and the AlertDialog has a different background color. Let me see if I can adjust that

**Comment by alexrabin** [comment]
@maxland255 I upgraded my flutter version and I am no longer seeing that vertical line:

Screenshot 2024-12-13 at 10 46 16 AM

Screenshot 2024-12-13 at 10 46 26 AM

**Comment by maxland255** [comment]
> @maxland255 I upgraded my flutter version and I am no longer seeing that vertical line:
> 
> 
> 
> Screenshot 2024-12-13 at 10 46 16 AM
> 
> 
> 
> Screenshot 2024-12-13 at 10 46 26 AM
> 
> 
> 
> 

Okay perfect 👌

**Comment by alexrabin** [comment]
@maxland255 What are the next steps?

**Comment by maxland255** [comment]
If you can just change the code in my review
`debugMode: false` to `debugMode: debugMode`
and after I merge the pull request

**Comment by alexrabin** [comment]
Oh I'm not seeing your review but I can make that change.

**Comment by alexrabin** [comment]
@maxland255  fixed!

**Pull request merged**
